<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * UserCarSelectedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCarSelectedRepository extends EntityRepository
{
}